AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gc07_check_secure_network_transmission_policy

Globals:
  Function:
    Timeout: 90
    MemorySize: 128

Resources:
  GC07CheckSecureNetworkTransmissionPolicyLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
