AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gc11_check_policy_event_logging

Globals:
  Function:
    Timeout: 90
    MemorySize: 128

Resources:
  GC11CheckPolicyEventLoggingLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
