AWSTemplateFormatVersion: 2010-09-09
Description: Configures AWS Config and AWS Audit Manager for multi-account management.

Parameters:
  OrganizationName:
    Type: String
    Default: ""
    Description: The name of the organization. Used as a prefix in resource names.
  AuditAccountID:
    Type: String
    Default: ""
    Description: 12-digit AWS Account ID (e.g., '222222222222')
  RolePrefix:
    Type: String
    Default: "ASEA-"
    Description: >-
      The prefix to apply to generated role names, in ASEA this is generally ASEA- for lza this could be cdk-accel etc
  PythonRuntime:
    Type: String
    Default: "python3.12"
    Description: The python runtime to use for the compliance dashboard
  DefaultCloudProfile:
    Type: String
    Description: The cloud profile to use when one is not provided by an account.

Conditions:
  IsAuditAccount: !Equals
    - !Ref AWS::AccountId
    - !Ref AuditAccountID

Resources:
  CloudGuardrailsCommonLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: CloudGuardrailsCommonLayerPart6
      CompatibleRuntimes:
        - python3.12
      Content: "../../src/layer/cloud_guardrails/build/CloudGuardrailsCommonLayer/"

  GC07CheckCertificateAuthoritiesLambda:
    Condition: IsAuditAccount
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${OrganizationName}gc07_check_certificate_authorities"
      Code: "../../src/lambda/gc07_check_certificate_authorities/build/GC07CheckCertificateAuthoritiesLambda/"
      Handler: app.lambda_handler
      Role: !Sub "arn:aws:iam::${AuditAccountID}:role/${RolePrefix}default_assessment_role"
      Runtime: !Ref PythonRuntime
      Timeout: 600
      Layers:
        - !Ref CloudGuardrailsCommonLayer
      LoggingConfig:
        LogGroup: !Sub "${OrganizationName}gc_guardrails"
        LogFormat: "JSON"
      Environment:
        Variables:
          DEFAULT_CLOUD_PROFILE: !Ref DefaultCloudProfile

  GC07CheckCryptographicAlgorithmsLambda:
    Condition: IsAuditAccount
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${OrganizationName}gc07_check_cryptographic_algorithms"
      Code: "../../src/lambda/gc07_check_cryptographic_algorithms/build/GC07CheckCryptographicAlgorithmsLambda/"
      Handler: app.lambda_handler
      Role: !Sub "arn:aws:iam::${AuditAccountID}:role/${RolePrefix}default_assessment_role"
      Runtime: !Ref PythonRuntime
      Timeout: 600
      Layers:
        - !Ref CloudGuardrailsCommonLayer
      LoggingConfig:
        LogGroup: !Sub "${OrganizationName}gc_guardrails"
        LogFormat: "JSON"
      Environment:
        Variables:
          DEFAULT_CLOUD_PROFILE: !Ref DefaultCloudProfile

  GC07CheckEncryptionInTransitLambda:
    Condition: IsAuditAccount
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${OrganizationName}gc07_check_encryption_in_transit"
      Code: "../../src/lambda/gc07_check_encryption_in_transit/build/GC07CheckEncryptionInTransitLambda/"
      Handler: app.lambda_handler
      Role: !Sub "arn:aws:iam::${AuditAccountID}:role/${RolePrefix}default_assessment_role"
      Runtime: !Ref PythonRuntime
      Timeout: 600
      Layers:
        - !Ref CloudGuardrailsCommonLayer
      LoggingConfig:
        LogGroup: !Sub "${OrganizationName}gc_guardrails"
        LogFormat: "JSON"
      Environment:
        Variables:
          DEFAULT_CLOUD_PROFILE: !Ref DefaultCloudProfile
