AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to deploy the GC Guardrails Organizational Role Generator

Parameters:
  OrganizationName:
    Type: String
    Default: ""
    Description: The name of the organization. Used as a prefix in resource names.
  AuditAccountID:
    Type: String
    Description: >-
      The AWS Account ID (12 digits) of the Audit Account
  ClientEvidenceBucket:
    Type: String
    Description: >-
      The name of the Amazon S3 bucket to be created to store the required documents for assessment.
  AWSConfigConformsBucketName:
    Type: String
    Description: >-
      The name of the Amazon S3 bucket used for the conformance pack deployment .
  RolePrefix:
    Type: String
    Default: "ASEA-"
    Description: >-
      The prefix to apply to generated role names, in ASEA this is generally ASEA- for lza this could be cdk-accel etc
  AccelRolePrefix:
    Type: String
    Default: "AWSA-"
    Description: >-
      The Accelerator role prefix for privileged access, in ASEA or LZA deployed by Proservices this could be AWSA- etc
  AcceleratorRole:
    Type: String
    Description: >-
      The role used to assume access to organizational accounts, in ASEA = ASEA-PipelineRole, LZA = OrganizationAccountAccessRole could also be PBMMAccel etc.
  PythonRuntime:
    Type: String
    Default: 'python3.12'
    Description:
      The python runtime to use for the compliance dashboard

Resources:
  LambdaCreateRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: self_invoke
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunctionUrl
                  - lambda:InvokeFunction
                  - lambda:GetFunctionEventInvokeConfig
                  - lambda:GetFunction
                  - lambda:InvokeAsync
                  - lambda:GetAlias
                Resource: !Sub "arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:${OrganizationName}aws_create_role"
              - Effect: Allow
                Action:
                  - lambda:ListFunctions
                Resource: "*"
        - PolicyName: assume_role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:iam::*:role/${AcceleratorRole}
              - Effect: Allow
                Action:
                  - "organizations:Describe*"
                  - "organizations:List*"
                Resource:
                  - "*"
  CreateRoleLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Sub ${OrganizationName}aws_org_create_role
      Handler: index.lambda_handler
      Role: !GetAtt LambdaCreateRole.Arn
      Runtime: !Ref PythonRuntime
      Timeout: 900
      Code: "../../src/lambda/aws_create_role/build/CreateRoleLambda/"


  EventBridgeCreateAccount:
    Type: AWS::Events::Rule
    Properties: 
      Description: !Sub ${OrganizationName}-New-Account-Role-Trigger
      EventPattern: 
            source: 
              - "aws.organizations"
            detail: 
              eventName:
                - "CreateAccountResult"
              eventSource:
                - "organizations.amazonaws.com"
              serviceEventDetails:
                createAccountStatus:
                  state:
                    - SUCCEEDED
      State: "ENABLED"
      Targets: 
        - 
          Arn: !GetAtt CreateRoleLambda.Arn
          Id: "TargetFunctionV1"
          Input: !Sub |-
              {
                
                "Roles": [
                  {
                    "Name": "${AccelRolePrefix}GCLambdaExecutionRole2",
                    "TrustPrincipal": "arn:${AWS::Partition}:iam::${AuditAccountID}:root",
                    "SwitchRole": "${AcceleratorRole}",
                    "PolicyPackage": {
                      "Docs": [{
                        "Version": "2012-10-17",
                        "Statement": [{
                          "Action": [
                            "acm:Describe*",
                            "acm:Get*",
                            "acm:List*",
                            "apigateway:GET", 
                            "backup:ListBackupVaults",
                            "backup:ListRecoveryPointsByBackupVault",
                            "cassandra:Select",
                            "cloudfront:Describe*",
                            "cloudfront:Get*",
                            "cloudfront:List*",
                            "cloudtrail:DescribeTrails",
                            "cloudtrail:Get*",
                            "cloudtrail:ListTrails",
                            "cloudtrail:LookupEvents",
                            "codebuild:BatchGetProjects",
                            "codebuild:ListProjects",
                            "config:PutEvaluations",
                            "docdb-elastic:List*",
                            "dynamodb:DescribeTable",
                            "dynamodb:ListTables",
                            "ec2:Describe*",
                            "ec2:GetEbsEncryptionByDefault",
                            "eks:DescribeCluster",
                            "eks:ListClusters",
                            "elasticache:Describe*",
                            "elasticfilesystem:DescribeFileSystems",
                            "elasticloadbalancing:Describe*",
                            "es:DescribeElasticsearchDomains",  
                            "es:ListDomainNames",
                            "kinesis:DescribeStream",
                            "kinesis:ListStreams",
                            "memorydb:Describe*",
                            "organizations:Describe*",
                            "organizations:List*",
                            "qldb:DescribeLedger",
                            "qldb:ListLedgers",
                            "rds:Describe*",
                            "redshift:Describe*",
                            "resource-explorer-2:ListIndexes",
                            "resource-explorer-2:Search",
                            "s3:Get*",
                            "s3:List*",
                            "sns:GetTopicAttributes",
                            "sns:ListTopics",
                            "tag:GetResources",
                            "timestream:DescribeEndpoints",
                            "timestream:List*"
                          ],
                          "Resource": [
                            "*"
                          ],
                          "Effect": "Allow",
                          "Sid": "GCComplianceAllowAccess2"
                        }]
                      }]
                    }
                  },
                  {
                    "Name": "${AccelRolePrefix}GCLambdaExecutionRole",
                    "TrustPrincipal": "arn:${AWS::Partition}:iam::${AuditAccountID}:root",
                    "SwitchRole": "${AcceleratorRole}",
                    "PolicyPackage": {
                        "Docs": [{
                          "Version": "2012-10-17",
                            "Statement": [{
                              "Action": [
                                "acm:Describe*",
                                "acm:Get*",
                                "acm:List*",
                                "apigateway:GET",
                                "aws-marketplace:ListEntities",
                                "backup:List*",
                                "cassandra:Select",
                                "cloudfront:Describe*",
                                "cloudfront:Get*",
                                "cloudfront:List*",
                                "cloudtrail:DescribeTrails",
                                "cloudtrail:Get*",
                                "cloudtrail:ListTrails",
                                "cloudtrail:LookupEvents",
                                "codebuild:BatchGetProjects",
                                "codebuild:ListProjects",
                                "config:PutEvaluations",
                                "dax:DescribeClusters",
                                "docdb-elastic:ListClusters",
                                "docdb-elastic:ListClusterSnapshots",
                                "dynamodb:DescribeTable",
                                "dynamodb:ListTables",
                                "ec2:Describe*",
                                "ec2:GetEbsEncryptionByDefault",
                                "eks:DescribeCluster",
                                "eks:ListClusters",
                                "elasticache:Describe*",
                                "elasticfilesystem:DescribeFileSystems",
                                "iam:GenerateCredentialReport",
                                "iam:Get*",
                                "iam:List*",
                                "iam:Simulate*",
                                "kinesis:DescribeStream",
                                "kinesis:ListStreams",
                                "memorydb:Describe*",
                                "organizations:Describe*",
                                "organizations:List*",
                                "qldb:DescribeLedger",
                                "qldb:ListLedgers",
                                "rds:Describe*",
                                "resource-explorer-2:ListIndexes",
                                "resource-explorer-2:Search",
                                "s3:Get*",
                                "s3:List*",
                                "sns:GetTopicAttributes",
                                "sns:ListTopics",
                                "tag:GetResources",
                                "timestream:DescribeEndpoints",
                                "timestream:List*"
                              ],
                              "Resource": [
                                "*"
                              ],
                              "Effect": "Allow",
                              "Sid": "GCComplianceAllowAccess"
                            },
                            {
                              "Action": [
                                "s3:Get*",
                                "s3:ListBucket"
                              ],
                              "Resource": [
                                "arn:${AWS::Partition}:s3:::${AWSConfigConformsBucketName}",
                                "arn:${AWS::Partition}:s3:::${AWSConfigConformsBucketName}/*",
                                "arn:${AWS::Partition}:s3:::${ClientEvidenceBucket}",
                                "arn:${AWS::Partition}:s3:::${ClientEvidenceBucket}/*"
                              ],
                              "Effect": "Allow",
                              "Sid": "GcComplianceAllowBucketAccess"
                            },
                            {
                              "Action": [
                                "account:GetAlternateContact"
                              ],
                              "Resource": [
                                "arn:aws:account::*:account",
                                "arn:aws:account::*:account/o-*/*"
                              ],
                              "Effect": "Allow",
                              "Sid": "AllowReadAccountInfo"
                            },
                            {
                              "Action": [
                                "s3:ListAllMyBuckets"
                              ],
                              "Resource": "*",
                              "Effect": "Allow",
                              "Sid": "GcComplianceAllowListBucketAccess"
                            }
                          ]
                        }]
                      }
                  }
                ] 
              }

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "CreateRoleLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventBridgeCreateAccount.Arn
