AWSTemplateFormatVersion: 2010-09-09
Description: "Fed Client root resource cfn stack."

Parameters:
  ApiKey:
    Type: String
    Default: "*API_KEY*"
  ApiUrl:
    Type: String
    Default: "*API_URL*"
  Email:
    Type: String
    Default: "*CSPM_EMAIL*"
    Description: Subject to change, might not be used here
  DefaultCloudProfile:
    Type: String
    Default: "3"
    AllowedValues: [ "1", "2", "3", "4", "5", "6"]
  OrganizationId:
    Type: String
    Default: "*ORG_ID*"
    Description: Primary identifier for metadata of registered org
  TenantId:
    Type: String
    Default: "*TENANT_ID*"
  InvokeUpdate:
    Type: String
    Default: "17d78b5e-9745-41e4-a926-9fd9f660bf23"
    Description: UUID to trigger updates
  ExecutionName:
    Type: String
    Default: "gc-fedclient-copy-execution-role"
  ExecutionName2:
    Type: String
    Default: "gc-fedclient-evidence-copy-execution-role"
  RootOUID:
    Type: String
    Default: "r-bv5z"
  SecurityOUID:
    Type: String
    Default: "**SECURITY_OUID**"
  AuditAccountID:
    Type: String
    Default: "**AUDIT_ACCOUNT_ID**"
  BGA1:
    Type: String
    Default: "bgUser1"
  BGA2:
    Type: String
    Default: "bgUser2"
  OrganizationName:
    Type: String
    Default: "SSC-Test"
  RolePrefix:
    Type: String
    Default: "gc-"
    Description: >-
      The prefix to apply to generated role names, it is optional to set this
  AccelRolePrefix:
    Type: String
    Default: "ASEA-"
    Description: >-
      The Accelerator role prefix for privileged access, in ASEA or LZA deployed by Proservices this could be AWSA-
  AcceleratorRole:
    Type: String
    Description: >-
      The role used to assume access to organizational accounts, in ASEA = ASEA-PipelineRole, LZA = OrganizationAccountAccessRole could also be PBMMAccel etc. This is not optional
    Default: "ASEA-PipelineRole"
  PipelineBucket:
    Type: String
    Description: >-
      The deployment pipeline bucket holding child templates and packaged lambda code.
  DestBucketName:
    Type: String
    Default: "*GCDestBucketName*"
    Description: Bucket to which evidence will be shared
  DeployRoles:
    Type: String
    Default: true
    AllowedValues: [true, false]
  DeployVersion:
    Type: String
    Default: 2.0.0

Resources:
  GuardRailsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${PipelineBucket}.s3.${AWS::Region}.amazonaws.com/${DeployVersion}/main.yaml
      Parameters:
        ExecutionName: !Ref ExecutionName
        ExecutionName2: !Ref ExecutionName2
        OrganizationId: !Ref OrganizationId
        OrganizationName: !Ref OrganizationName
        TenantId: !Ref TenantId
        RolePrefix: !Ref RolePrefix
        DefaultCloudProfile: !Ref DefaultCloudProfile
        AccelRolePrefix: !Ref AccelRolePrefix
        AcceleratorRole: !Ref AcceleratorRole
        SecurityOUID: !Ref SecurityOUID
        AuditAccountID: !Ref AuditAccountID
        RootOUID: !Ref RootOUID
        PipelineBucket: !Ref PipelineBucket
        DestBucketName: !Ref DestBucketName
        DeployRoles: !Ref DeployRoles
        DeployVersion: !Ref DeployVersion
        InvokeUpdate: !Ref InvokeUpdate
        BGA1: !Ref BGA1
        BGA2: !Ref BGA2
      Tags:
        - Key: "UpdateTrigger"
          Value: !Ref InvokeUpdate
        - Key: "DeployVersion"
          Value: !Ref DeployVersion
